package statemanager

var (
	BASE                         = "START"
	SAVE_DEFINITION_WAIT_NAME    = "SAVE_DEFINITION_WAIT_NAME"
	SAVE_DEFINITION_WAIT_MEANING = "SAVE_DEFINITION_WAIT_MEANING"
	SAVE_DEFINITION_WAIT_TAG     = "SAVE_DEFINITION_WAIT_TAG"

	GET_DEFINITIONS_WAIT         = "GET_DEFINITIONS"
)
